### ISSUE TITLE
[FR] - Haddock link

### ISSUE THREAD

**Issue by sourabhxyz** [input-output-hk/cardano-api#188]
**Internal/External**

*External* 

**Area**

*Other*

**Describe the feature you'd like**

Usually IOG libraries have haddock hosted like https://input-output-hk.github.io/plutus/master/ but I couldn't find the same for `cardano-api`. I have seen [this](https://input-output-hk.github.io/cardano-node/cardano-api/lib/) but that's tracking an older version.

**Comment by smelc** [comment]
This is in the work: see https://github.com/input-output-hk/cardano-api/pull/241

**Comment by sourabhxyz** [comment]
Thanks @smelc.
