### ISSUE TITLE
[BUG] - Impossible to satisfy interface on TxBody

### ISSUE THREAD

**Issue by ch1bo** [input-output-hk/cardano-api#376]
*Internal*

**Area**
Haskell API Code

**Summary**
[This recent change](https://github.com/input-output-hk/cardano-api/commit/35014c294e261150dfa7e45ec4ab737e512c3f0f) in the data constructors of `TxBody era` makes it impossible, hard or at least annoying to work with this type. 

Casing on `TxBody` constructors degraded by this change and if matched completely, leads to "inaccessible code". See [this example](https://github.com/input-output-hk/hydra/blob/e4714ec3bec00d01f00c3f3461c56c946b04e6be/hydra-cardano-api/src/Hydra/Cardano/Api/Tx.hs#L63-L64) and screenshot:

![image](https://github.com/input-output-hk/cardano-api/assets/2621189/5fde0726-18ee-4eeb-b424-510c821a1b46)

**Steps to reproduce**
1. Use the `TxBody` data type

**Expected behavior**
Proper GADT constructors like before, which allow the compiler to infer `era ~ ByronEra` on the `ByronTxBody` data constructor. This results in even a single possible pattern match on `TxBody` and simplifies usage of `cardano-api`.

**System info (please complete the following information):**
N/A

**Comment by Jimbo4350** [comment]
Resolved by isolating Byron related transaction building code.
